### ISSUE TITLE
KeyError: 'GLOBAL'

### ISSUE THREAD

**Issue by MrClanck** [thibaultspriet/SyncNotionCalendar#13]
I just tried the installation, but after answering every questions it tell me that : 

Traceback (most recent call last):
  File "/Users/noe/Documents/Scripts/SyncNotionCalendar/main.py", line 29, in <module>
    notion_token = conf['GLOBAL']['NOTION_TOKEN']
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/configparser.py", line 964, in __getitem__
    raise KeyError(key)
KeyError: 'GLOBAL'

Did I make a mistake ? 
To be honest, I'm not quit sure what "Enter the calendar name you want to sync : " really means.
Same with the database name, could it be an issue with the emoji ? (I use the one from Notion, not in the title directly)

**Comment by thibaultspriet** [comment]
Hey @MrClanck,

The error has been fixed. You can pull new changes and run install.sh again.

For the calendar name it must be the name in your apple calendar app. (for example Personnel or Notion in my case)
<img width="363" alt="Capture d’écran 2022-08-18 à 15 16 39" src="https://user-images.githubusercontent.com/62113701/185476469-478ced4b-9e60-4072-baa8-1f92789232e5.png">

Then the database name you can put what you want (it doesn't need to be the same as the title of your database in Notion). However I advice not to put emoji in this name.

Hope it will works.

**Comment by noebourdin** [comment]
Ok so thank you for your fast response, but know that i have reinstall everything, i have another issue : 

Synchronisation of your databases ....
Traceback (most recent call last):
  File "/Users/noe/Documents/Scripts/SyncNotionCalendar/src/notionClient.py", line 115, in get_live_cards
    _list_page += q.json()['results']
KeyError: 'results'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/noe/Documents/Scripts/SyncNotionCalendar/main.py", line 34, in <module>
    db.run()
  File "/Users/noe/Documents/Scripts/SyncNotionCalendar/src/Database.py", line 213, in run
    live = self.get_live()
  File "/Users/noe/Documents/Scripts/SyncNotionCalendar/src/Database.py", line 70, in get_live
    current_cards = self.notion_client.get_live_cards(self.id)
  File "/Users/noe/Documents/Scripts/SyncNotionCalendar/src/notionClient.py", line 118, in get_live_cards
    raise Exception(q.text)
Exception: {"object":"error","status":400,"code":"validation_error","message":"Could not find property with name or id: date"}

**Comment by thibaultspriet** [comment]
You can get the solution [here](https://github.com/thibaultspriet/SyncNotionCalendar/issues/7#issuecomment-1098417331).

**Comment by noebourdin** [comment]
Oh ok, the thing is, my date is in a Formula property, but I am gonna check if it works if named "date"

**Comment by noebourdin** [comment]
Yeah so know it tells me that : 

Synchronisation of your databases ....
Traceback (most recent call last):
  File "/Users/noe/Documents/Scripts/SyncNotionCalendar/main.py", line 34, in <module>
    db.run()
  File "/Users/noe/Documents/Scripts/SyncNotionCalendar/src/Database.py", line 213, in run
    live = self.get_live()
  File "/Users/noe/Documents/Scripts/SyncNotionCalendar/src/Database.py", line 70, in get_live
    current_cards = self.notion_client.get_live_cards(self.id)
  File "/Users/noe/Documents/Scripts/SyncNotionCalendar/src/notionClient.py", line 121, in get_live_cards
    _list_card = [Card(page) for page in _list_page]
  File "/Users/noe/Documents/Scripts/SyncNotionCalendar/src/notionClient.py", line 121, in <listcomp>
    _list_card = [Card(page) for page in _list_page]
  File "/Users/noe/Documents/Scripts/SyncNotionCalendar/src/notionClient.py", line 24, in __init__
    self.title = page.get('properties').get('Name').get('title')[0].get('plain_text')
AttributeError: 'NoneType' object has no attribute 'get'

**Comment by thibaultspriet** [comment]
Is your title column named "Name" ?

**Comment by noebourdin** [comment]
I have a formula property called "Next Rep" which calculate the next date for an event, and I would like to add that date to iCal.

**Comment by noebourdin** [comment]
![096E3DD5-1884-4BB0-B9C2-D35E27729561](https://user-images.githubusercontent.com/55362787/185486484-0ab54546-2237-4f33-8212-78741596dbf5.jpeg)

Here is my property list

**Comment by thibaultspriet** [comment]
I will work to add the ability to name the date property as you want.

However it will take some time. If you want the software working now I recommend you to name the property "date".

I will notice you when the feature will be ready

**Comment by thibaultspriet** [comment]
You can also replace :
- 'Name' by 'Leçon'
- 'date' by 'Next Rep'

In the file src/notionClient.py

![image](https://user-images.githubusercontent.com/62113701/185489699-5c3131bd-905b-498a-9242-03908781a141.jpeg)

**Comment by noebourdin** [comment]
Same issue : 

Traceback (most recent call last):
  File "/Users/noe/Documents/Scripts/SyncNotionCalendar/main.py", line 34, in <module>
    db.run()
  File "/Users/noe/Documents/Scripts/SyncNotionCalendar/src/Database.py", line 213, in run
    live = self.get_live()
  File "/Users/noe/Documents/Scripts/SyncNotionCalendar/src/Database.py", line 70, in get_live
    current_cards = self.notion_client.get_live_cards(self.id)
  File "/Users/noe/Documents/Scripts/SyncNotionCalendar/src/notionClient.py", line 121, in get_live_cards
    _list_card = [Card(page) for page in _list_page]
  File "/Users/noe/Documents/Scripts/SyncNotionCalendar/src/notionClient.py", line 121, in <listcomp>
    _list_card = [Card(page) for page in _list_page]
  File "/Users/noe/Documents/Scripts/SyncNotionCalendar/src/notionClient.py", line 26, in __init__
    self.start_date = self._convert_datetime(page.get('properties').get('Next Rep').get('date').get('start'))
AttributeError: 'NoneType' object has no attribute 'get'

It worked when I tried to rename "Date appris" in "date" before changing de code, but it didn't show anything on iCal.
