### ISSUE TITLE
"Could not find property with name or id: date"

### ISSUE THREAD

**Issue by thibaultspriet** [thibaultspriet/SyncNotionCalendar#14]
Ok so thank you for your fast response, but know that i have reinstall everything, i have another issue : 

Synchronisation of your databases ....
Traceback (most recent call last):
  File "/Users/noe/Documents/Scripts/SyncNotionCalendar/src/notionClient.py", line 115, in get_live_cards
    _list_page += q.json()['results']
KeyError: 'results'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/noe/Documents/Scripts/SyncNotionCalendar/main.py", line 34, in <module>
    db.run()
  File "/Users/noe/Documents/Scripts/SyncNotionCalendar/src/Database.py", line 213, in run
    live = self.get_live()
  File "/Users/noe/Documents/Scripts/SyncNotionCalendar/src/Database.py", line 70, in get_live
    current_cards = self.notion_client.get_live_cards(self.id)
  File "/Users/noe/Documents/Scripts/SyncNotionCalendar/src/notionClient.py", line 118, in get_live_cards
    raise Exception(q.text)
Exception: {"object":"error","status":400,"code":"validation_error","message":"Could not find property with name or id: date"}

__Originally posted by @MrClanck in https://github.com/thibaultspriet/SyncNotionCalendar/issues/13#issuecomment-1219877990__

**Comment by thibaultspriet** [comment]
Please see the fix in this [issue](https://github.com/thibaultspriet/SyncNotionCalendar/issues/7#issuecomment-1098417331)
