### ISSUE TITLE
Error when initializing the database sync

### ISSUE THREAD

**Issue by ollibrinks** [thibaultspriet/SyncNotionCalendar#28]
Hey,
first of all, that for this automization!
I have some trouble getting it ready.
Within the database synchronisation some error occur. Maybe you can help here?
I checked the Database Id and the Token, they are fine. The Names of calendar and database has to be exat the same writing as in fronend, right? -Then they are also good.

Here is the Terminal output:

```
Synchronisation of your databases ....
Traceback (most recent call last):
  File "/Users/privat/Scripte/NotionSync/src/notionClient.py", line 115, in get_live_cards
    _list_page += q.json()['results']
                  ~~~~~~~~^^^^^^^^^^^
KeyError: 'results'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/privat/Scripte/NotionSync/main.py", line 34, in <module>
    db.run()
  File "/Users/privat/Scripte/NotionSync/src/Database.py", line 213, in run
    live = self.get_live()
           ^^^^^^^^^^^^^^^
  File "/Users/privat/Scripte/NotionSync/src/Database.py", line 70, in get_live
    current_cards = self.notion_client.get_live_cards(self.id)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/privat/Scripte/NotionSync/src/notionClient.py", line 118, in get_live_cards
    raise Exception(q.text)
Exception: {"object":"error","status":400,"code":"validation_error","message":"Could not find property with name or id: date"}
Installation done
```
I would really appreciate if you can help and tell me what to do here. Thanks!
Donation will be made, be sure :)

Best regards

Oliver

**Comment by jgpearce1** [comment]
Hi Oliver, did you find a solution to this issue? I'm getting a similar thing. I've pasted my output below - 

```
Synchronisation of your databases ....
Traceback (most recent call last):
  File "/Users/Jess/Scripts/SyncNotionCalendar/src/notionClient.py", line 115, in get_live_cards
    _list_page += q.json()['results']
KeyError: 'results'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/Jess/Scripts/SyncNotionCalendar/main.py", line 34, in <module>
    db.run()
  File "/Users/Jess/Scripts/SyncNotionCalendar/src/Database.py", line 213, in run
    live = self.get_live()
  File "/Users/Jess/Scripts/SyncNotionCalendar/src/Database.py", line 70, in get_live
    current_cards = self.notion_client.get_live_cards(self.id)
  File "/Users/Jess/Scripts/SyncNotionCalendar/src/notionClient.py", line 118, in get_live_cards
    raise Exception(q.text)
Exception: {"object":"error","status":400,"code":"validation_error","message":"Could not find property with name or id: date","request_id":"abb43622-a58b-4804-bde4-171a7b411fc2"}
Installation done
```

**Comment by dearlsh94** [comment]
Hello, I just had faced the same issue, and here is how I solved.
This was caused by the property name, it supposed to be named as "date". 
If your desired notion database have the property name different from "date", then you should change to "date" exactly. 

checkout this issue
https://github.com/thibaultspriet/SyncNotionCalendar/issues/7#issuecomment-1098417331

**Comment by thibaultspriet** [comment]
Hey @ollibrinks @jgpearce1 and @dearlsh94 

I finally have good news: I found a way to make it work **without any local installation**.

I'm building a hosted version where you just connect your Notion and calendar accounts. No setup, no terminal, no "works on my machine" issues.

Quick questions (would really help me):

1. Is this still a problem you'd want solved?
2. Would you pay $5-10/month for a "it just works" solution?

No pressure to reply - but if you're still interested, I'd love your input before I build this.

Cheers,
Thibault
