### ISSUE TITLE
main.py script not working

### ISSUE THREAD

**Issue by DeusApotheosis** [thibaultspriet/SyncNotionCalendar#4]
<img width="1126" alt="Screenshot 2022-03-01 at 12 43 00 AM" src="https://user-images.githubusercontent.com/71841597/156022746-312dd6f2-4c84-4729-93ab-e74554bff616.png">

**Comment by ashmotif200** [comment]
<img width="1034" alt="Capture d’écran 2022-03-01 à 12 13 37" src="https://user-images.githubusercontent.com/65541608/156159276-f1a52cb1-1ece-4c77-bca0-bd012b91f4e6.png">

**Comment by thibaultspriet** [comment]
Hi !
I've just committed a fix. Can you pull or download the project and give an other try ?

Please tell me if the error persist or if it is solved

**Comment by ashmotif200** [comment]
Hello, after pulling the latest version I got this error at first.

```
/Users/ashley/Documents/Programming/SyncNotionCalendar/syncNotionCalendar.zsh
Traceback (most recent call last):
  File "/Users/ashley/Documents/Programming/SyncNotionCalendar/main.py", line 14, in <module>
    with open(log_file,'a') as f_ : pass # Create the log file
FileNotFoundError: [Errno 2] No such file or directory: '/Users/ashley/Documents/Programming/SyncNotionCalendar/logs/2022-03-03T19:30:41.log'
```

I created a folder called "logs" at root and this error disappeared then another one appeared.

```
/Users/ashley/Documents/Programming/SyncNotionCalendar/syncNotionCalendar.zsh
Traceback (most recent call last):
  File "/Users/ashley/Documents/Programming/SyncNotionCalendar/main.py", line 27, in <module>
    notion_token = conf['GLOBAL']['NOTION_TOKEN']
  File "/usr/local/Cellar/python@3.9/3.9.9/Frameworks/Python.framework/Versions/3.9/lib/python3.9/configparser.py", line 963, in __getitem__
    raise KeyError(key)
KeyError: 'GLOBAL'
```

oh and btw the log files are empty...

**Comment by ashmotif200** [comment]
from log : 
INFO:root:Start database job
ERROR:root:while fetching cards on Notion : {q.text}

**Comment by ashmotif200** [comment]
<img width="911" alt="Capture d’écran 2022-03-03 à 20 41 01" src="https://user-images.githubusercontent.com/65541608/156640656-fc0b6268-d59c-4480-a399-d55f80ef2ef7.png">

**Comment by thibaultspriet** [comment]
1. Thanks to you I noticed that the folder `logs` was not pushed to GitHub and caused the issue. Thank you for that
2. For your second error, did you check that you have followed well this section of the [ReadMe](https://github.com/thibaultspriet/SyncNotionCalendar#config-file)? you must have a `config.ini` file at the root of the project.

**Comment by DeusApotheosis** [comment]
Thanks for solving the log file issue, but i got another one here.
<img width="845" alt="Screenshot 2022-03-06 at 4 05 25 PM" src="https://user-images.githubusercontent.com/71841597/156914702-a1370fb6-b039-4c40-85dc-163378380ea0.png">

**Comment by ashmotif200** [comment]
> * Thanks to you I noticed that the folder `logs` was not pushed to GitHub and caused the issue. Thank you for that
:)
> * For your second error, did you check that you have followed well this section of the [ReadMe](https://github.com/thibaultspriet/SyncNotionCalendar#config-file)? you must have a `config.ini` file at the root of the project.
yep I filled the config according to the ReadMe.

**Comment by thibaultspriet** [comment]
Hi @ashmotif200, can you please add a screenshot of your file structure. Additionally can you copy paste content of your config.ini file (make sure to replace your personal tokens with placeholders)

**Comment by yyan4849** [comment]
Hi, when I run main.py, it raises an issue said as the pic below:
<img width="641" alt="截屏2022-04-01 14 28 42" src="https://user-images.githubusercontent.com/57382273/161207475-b9ee7e70-6018-4ec4-9e06-69c7d5e9d1e4.png">

**Comment by thibaultspriet** [comment]
Hi @yyan4849,
Please check this issue #7
